name = "hello"
main = "worker.js"
compatibility_date = "2023-08-23"

[unsafe.metadata.observability]
enabled = true
compatibility_flags = ["nodejs_compat"]

[vars]
MICROSERVICE_URL = "http://puzzle-app-microservice.braverock-6ea67e55.swedencentral.azurecontainerapps.io/results"
